module:
  code: XYZ123
  presentation: 99A
type: jupyter-notebook
packs:
  - openrefine
openrefine:
  version: '3.4.1' 
packages:
  pip:
    - jupyter-server-proxy
web_apps:
  - path:          openrefine
    cmdline:       /var/openrefine/refine -i 0.0.0.0 -p {port} -d $HOME/openrefine
